// <auto-generated />
using System;
using M5.API.PROJECT.Framework.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M5.API.PROJECT.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("M5.API.PROJECT.Framework.Domain.Aggregates.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("ProjectId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("M5.API.PROJECT.Framework.Domain.Aggregates.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("M5.API.PROJECT.Framework.Domain.Aggregates.Property", b =>
                {
                    b.Property<Guid>("ProjectId");

                    b.Property<string>("Key")
                        .HasMaxLength(50);

                    b.Property<string>("Value")
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ProjectId", "Key", "Value");

                    b.ToTable("Property");
                });

            modelBuilder.Entity("M5.API.PROJECT.Framework.Domain.Aggregates.Member", b =>
                {
                    b.HasOne("M5.API.PROJECT.Framework.Domain.Aggregates.Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("M5.API.PROJECT.Framework.Domain.Aggregates.Property", b =>
                {
                    b.HasOne("M5.API.PROJECT.Framework.Domain.Aggregates.Project")
                        .WithMany("Properties")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
