// <auto-generated />
using System;
using M5.API.LINK.Framework.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace M5.API.LINK.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20181017101408_INIT")]
    partial class INIT
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("M5.API.LINK.Framework.Domain.Aggregates.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("LinkId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("M5.API.LINK.Framework.Domain.Aggregates.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Link");
                });

            modelBuilder.Entity("M5.API.LINK.Framework.Domain.Aggregates.Contact", b =>
                {
                    b.HasOne("M5.API.LINK.Framework.Domain.Aggregates.Link")
                        .WithMany("Contacts")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
